// Every text the user sees, in both languages. Keys are flat; texts with parameters are functions.
// The "hu" values are the original texts of the Hungarian-only versions, kept word for word.

export type Lang = "en" | "hu";

export const LANGS: {id: Lang; label: string}[] = [
  {id: "en", label: "English"},
  {id: "hu", label: "Magyar"},
];

const en = {
  locale: "en-US", // number formatting

  // Main window: chips
  chipTimer: "Timer",
  chipStopwatch: "Stopwatch",
  chipGoal: "Goal",
  chipPomodoro: "Pomodoro",
  chipBack: "Back",
  chipCustom: "Custom",
  chipResume: "Resume",
  chipStop: "Stop",

  // Main window: helper lines under the time
  linePickMode: "Pick a mode",
  linePickDur: "Scroll, or click the number",
  lineAlarm: (target: string) => `Time's up, target ${target}`,
  lineAlarmClose: "Click to dismiss",
  lineFocusTime: "Focus time",
  linePomodoros: (n: number) => `${n} full ${n === 1 ? "pomodoro" : "pomodoros"}`,
  lineTotal: "Total",
  lineGoal: (target: string) => `Target ${target}`,
  lineRemaining: (time: string) => `${time} left`,
  lineOvertime: (time: string) => `Overtime +${time}`,
  lineGoalOvertime: (target: string, over: string) => `Target ${target}, +${over}`,
  lineBreak: "Break",
  lineFocus: (n: number) => `Focus · #${n}`,
  linePaused: "Paused",

  // Main window: buttons and Windows toasts
  settingsButton: "Settings",
  settingsWindowTitle: "FORBY – Settings",
  traySettings: "Settings",
  trayFind: "Find FORBY",
  trayQuit: "Quit",
  toastTimeUp: "Time's up",
  toastGoalReached: (target: string) => `Target reached (${target})`,
  toastBreak: "Break time",
  toastBackToFocus: "Back to focus",
  toastTest: "Test notification",

  // Built-in sounds and alarm events
  soundChime: "Chime",
  soundBell: "Bell",
  soundBeep: "Beep",
  soundGong: "Gong",
  eventTimeUp: "Time's up",
  eventBreakStart: "Break starts",
  eventBackToWork: "Back to work",

  // Settings window
  language: "Language",
  tabLook: "Appearance & timing",
  tabAlerts: "Alerts",
  close: "Close",
  orbColor: "Orb colour",
  customColor: "Custom colour",
  readingAnimation: "Reading animation while focused",
  pomodoroFocus: "Pomodoro focus",
  pomodoroBreak: "Pomodoro break",
  minutes: "min",
  playMode: "Play mode",
  autostart: "Start with Windows",
  sound: "Sound",
  volume: "Volume",
  eventSoundLabel: (event: string) => `${event}: sound`,
  previewLabel: (name: string) => `${name}: preview`,
  preview: "Preview",
  builtinSounds: "Built-in",
  customSounds: "Custom sounds",
  flashTaskbar: "Flash taskbar",
  notification: "Windows notification",
  jumpToCursor: "Jump to cursor",
  devTest: "Test (dev mode only)",
  testFlash: "Flash",
  testToast: "Notification",
  testJump: "Jump",

  // Custom sound library
  back: "Back",
  newName: "New name",
  renameTitle: (name: string) => `${name} (rename)`,
  seconds: "s",
  confirmDelete: "Delete?",
  deleteLabel: (name: string) => `${name}: delete`,
  delete: "Delete",
  recordStop: (left: number) => `Stop (${left})`,
  record: (maxSec: number) => `Record (max ${maxSec} s)`,
  uploadFile: "Upload a file",
  newSoundName: (n: number) => `Custom sound ${n}`,
  statusAdded: (name: string) => `“${name}” was added to the library. Assign it to an event in the sound pickers.`,
  statusDeleted: (name: string) => `“${name}” deleted.`,
  statusSwitched: (events: string, fallback: string) => ` ${events}: now ${fallback}.`,
  statusFull: (max: number) => `At most ${max} custom sounds; delete one to add another.`,
  statusEmpty: "No custom sounds yet.",
  errPlayback: "The sound cannot be played",
  errTooMany: (max: number) => `At most ${max} custom sounds`,
  errTooBig: "The file is larger than 5 MB",
  errNotAudio: "This file is not playable audio",
  errTooLong: (maxSec: number) => `The sound is longer than ${maxSec} s`,
  errSave: "Saving failed",
  errMic: "No access to the microphone",
  errFileType: (exts: string) => `Unsupported file type (${exts})`,
  errDelete: "Deleting failed",
};

export type Strings = typeof en;
// Keys whose value is a plain string (usable as a label without calling)
export type TextKey = {[K in keyof Strings]: Strings[K] extends string ? K : never}[keyof Strings];

const hu: Strings = {
  locale: "hu-HU",

  chipTimer: "Timer",
  chipStopwatch: "Stopper",
  chipGoal: "Cél-stopper",
  chipPomodoro: "Pomodoro",
  chipBack: "Vissza",
  chipCustom: "Egyéni",
  chipResume: "Folytat",
  chipStop: "Leállít",

  linePickMode: "Válassz módot",
  linePickDur: "Görgess, vagy kattints a számra",
  lineAlarm: (target) => `Lejárt, cél ${target}`,
  lineAlarmClose: "Kattints a lezáráshoz",
  lineFocusTime: "Fókuszidő",
  linePomodoros: (n) => `${n} teljes pomodoro`,
  lineTotal: "Összesen",
  lineGoal: (target) => `Cél ${target}`,
  lineRemaining: (time) => `${time} maradt`,
  lineOvertime: (time) => `Túlóra +${time}`,
  lineGoalOvertime: (target, over) => `Cél ${target}, +${over}`,
  lineBreak: "Szünet",
  lineFocus: (n) => `Fókusz · ${n}.`,
  linePaused: "Szünetel",

  settingsButton: "Beállítások",
  settingsWindowTitle: "FORBY – Beállítások",
  traySettings: "Beállítások",
  trayFind: "FORBY megkeresése",
  trayQuit: "Kilépés",
  toastTimeUp: "Lejárt az idő",
  toastGoalReached: (target) => `Elérted a célt (${target})`,
  toastBreak: "Szünet következik",
  toastBackToFocus: "Vissza a fókuszhoz",
  toastTest: "Teszt értesítés",

  soundChime: "Csengő",
  soundBell: "Harang",
  soundBeep: "Pittyegés",
  soundGong: "Gong",
  eventTimeUp: "Idő lejárt",
  eventBreakStart: "Szünet kezdődik",
  eventBackToWork: "Vissza a munkához",

  language: "Nyelv",
  tabLook: "Megjelenés és időzítés",
  tabAlerts: "Riasztások",
  close: "Bezárás",
  orbColor: "Gömb színe",
  customColor: "Egyedi szín",
  readingAnimation: "Olvasó animáció fókusz alatt",
  pomodoroFocus: "Pomodoro fókusz",
  pomodoroBreak: "Pomodoro szünet",
  minutes: "perc",
  playMode: "Játék mód",
  autostart: "Indítás a géppel",
  sound: "Hang",
  volume: "Hangerő",
  eventSoundLabel: (event) => `${event}: hang`,
  previewLabel: (name) => `${name}: előhallgatás`,
  preview: "Előhallgatás",
  builtinSounds: "Beépített",
  customSounds: "Saját hangok",
  flashTaskbar: "Tálca-villogás",
  notification: "Windows értesítés",
  jumpToCursor: "Odaugrik a kurzorhoz",
  devTest: "Teszt (csak fejlesztői módban)",
  testFlash: "Villogás",
  testToast: "Értesítés",
  testJump: "Odaugrás",

  back: "Vissza",
  newName: "Új név",
  renameTitle: (name) => `${name} (átnevezés)`,
  seconds: "mp",
  confirmDelete: "Törlöd?",
  deleteLabel: (name) => `${name}: törlés`,
  delete: "Törlés",
  recordStop: (left) => `Leállítás (${left})`,
  record: (maxSec) => `Felvétel (max ${maxSec} mp)`,
  uploadFile: "Fájl feltöltése",
  newSoundName: (n) => `Saját hang ${n}`,
  statusAdded: (name) => `„${name}” bekerült a könyvtárba. Eseményhez a hangválasztókban rendelheted hozzá.`,
  statusDeleted: (name) => `„${name}” törölve.`,
  statusSwitched: (events, fallback) => ` ${events}: ${fallback} lett.`,
  statusFull: (max) => `Legfeljebb ${max} saját hang lehet, újhoz törölj egyet.`,
  statusEmpty: "Még nincs saját hang.",
  errPlayback: "A hang nem játszható le",
  errTooMany: (max) => `Legfeljebb ${max} saját hang lehet`,
  errTooBig: "A fájl nagyobb 5 MB-nál",
  errNotAudio: "Ez a fájl nem lejátszható hang",
  errTooLong: (maxSec) => `A hang hosszabb ${maxSec} mp-nél`,
  errSave: "A mentés nem sikerült",
  errMic: "Nincs hozzáférés a mikrofonhoz",
  errFileType: (exts) => `Nem támogatott fájltípus (${exts})`,
  errDelete: "A törlés nem sikerült",
};

export const strings: Record<Lang, Strings> = {en, hu};
